"""empty message

Revision ID: 591d5916130f
Revises: 
Create Date: 2024-01-24 14:04:32.710241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591d5916130f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_kilowatts', sa.Float(), nullable=True))
        batch_op.alter_column('meter_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('mobile_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_number', sa.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('meter_number',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('remaining_kilowatts')

    # ### end Alembic commands ###
